### PR TITLE
Add index sampler

### PR DESCRIPTION
**Pull request by tigerygao**
No compiler errors, runs correctly independently on onlineGDB

### CODE REVIEW

**Comment by tigerygao** [comment]
[Create function to sample indices of matrices when breaking them up into sets](https://trello.com/c/bmgFf1rz/27-create-function-to-sample-indices-of-matrices-when-breaking-them-up-into-sets)

**Comment by sherman5** [comment]
Overall this is the right idea, but there are a few things from a design perspective...

1) I would implement a function in `math/random.h` with the signature `std::vector<unsigned> sample(const std::vector<unsigned> &elements, unsigned n)` that returns `n` unique samples from `elements`. This will clean up the sampling procedure nicely and will help make the code more readable, in general it is good to follow [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) as much as possible. In this case that means having one function for sampling from a set of numbers and another function for creating multiple  sets of indices

2) with the above function implemented, rather that keep track of those indices you have sampled, start with a vector containing all indices, and then take elements out of it as you sample, passing this master list into your sample function each time

3) for now, remove the section that balances the sets, and just include a check to see if you are sampling the last set, in that case just store the remaining unused indices as the final set (similar to how it was done in the R code)

**Comment by sherman5** [comment]
In `gaps::random::sample` it would be better to delete the sampled element from `elements` rather than store it in a separate vector. This way you don't have to wait to get lucky in order to have a valid sample. In fact, if you change the function signature to `sample(std::vector<unsigned> &elements, unsigned n)` then you don't have to worry about deleting the sampled elements back in the `sampleIndices` function.

Also since you are deleting elements from `toBeSampled` all you have to do for the final set is `sampleIndices.push_back(toBeSampled)`

**Comment by sherman5** [comment]
Overall looks good, just a few minor things to cleanup before merging

`gaps::random::sample`

1) the `elements.empty()` check at the beginning of the loop will only be true if `n > elements.size()`, this should never happen so we would want to exit with an error if that condition is true. I would replace this check with `GAPS_ASSERT(n <= elements.size())` at the beginning of the function.
2) using `erase` for a vector is a little overkill for this situation since it requires any elements after the one you're erasing to be shifted. An alternative would be,
```
elements[sampleIndex] = elements.back();
elements.pop_back();
```
we can do this since we don't care about order within the vector.

`sampleIndices`
1) for clarity I would explicitly declare `unsigned setSize = n / nSets;` in the beginning of the function.
2) the second for loop (line 23) should stop at `nSets - 1`
3) If setSize is calculated correctly, the `toBeSampled.empty()` shouldn't be neccesary, up to you to keep it or not, but if you do I would change it to `GAPS_ASSERT(!toBeSampled.empty())` since we would want to fail with an error in this case

**Pull request merged**
